version: '3'
services: 
  web:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./public:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/nginx.conf
    restart: unless-stopped